server:
  servlet:
    context-path: /demo
  port: 8081

security:
  oauth2:
    client:
      client-id: demo-id
      client-secret: demo-secret
      scope: password

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/demo
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
  mail:
    from: changeit
    host: smtp.gmail.com
    port: 587
    username: changeit
    password: changeit
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file: demo.log
  level:
    com.code.demo: DEBUG